service:
  name: "buyer service"
  host: "localhost"
  port: 8082
bank:
  host: "localhost"
  port: 8081
database:
  host: "localhost"
  port: 5432
  dbname: "chan_db_test"
  user: "postgres"
  password: "postgres"
